#version 450
layout (local_size_x = 16, local_size_y = 16) in;
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

// Adapted from https://www.shadertoy.com/view/4ssfDj

#define PI 3.14159;

layout( push_constant ) uniform constants
{
 vec4 data1;
 vec4 data2;
 vec4 data3;
 vec4 data4;
} PushConstants;

float circ(vec2 p) {
	float r = length(p);
    r = sqrt(r);
    
    return abs(8. * r * fract(PushConstants.data3.x));
}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
	vec2 iResolution = imageSize(image);
	vec2 uv = (fragCoord - .5 * iResolution.xy) / iResolution.y;
   	vec3 color = vec3(.0);
    
    float rz = 1.;
    
    rz *= abs(circ(uv));
    
    color = vec3(.2, .2, .2) / rz;
    
	fragColor = vec4(color, 1.0);
}

void main() 
{
	vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color;
        mainImage(color,texelCoord);

    
        imageStore(image, texelCoord, color);
    }   
}