#version 450
layout (local_size_x = 16, local_size_y = 16) in;
layout(rgba16f,set = 0, binding = 0) uniform image2D image;

// Adapted from https://www.shadertoy.com/view/7lKSDz

layout( push_constant ) uniform constants
{
 vec4 data1;
 vec4 data2;
 vec4 data3;
 vec4 data4;
} PushConstants;


const float PI = 3.1415925358;

float safety_sin( in float x ) { return sin( mod( x, PI ) ); }

float rand( vec2 p ) { return fract( safety_sin( dot(p, vec2( 12.9898, 78.233 ) ) ) * 43758.5453 + PushConstants.data1.x * .35 ); }

float noise( vec2 x )
{
	vec2 i = floor(x);
	vec2 f = fract(x);
	vec4 h;
	// Smooth Interpolation
	f = f * f * ( f * -2.0 + 3.0 );
	// Four corners in 2D of a tile
	h.x = rand( i + vec2( 0., 0. ) );
	h.y = rand( i + vec2( 1., 0. ) );
	h.z = rand( i + vec2( 0., 1. ) );
	h.w = rand( i + vec2( 1., 1. ) );
	// Mix 4 coorners porcentages
	return mix( mix( h.x, h.y, f.x ), mix( h.z, h.w, f.x ), f.y );
}

float star_burst( vec2 p )
{
	float k0 = 2.0;
	float k1 = 1.0;
	float k2 = 0.5;
	float k3 = 12.0;
	float k4 = 12.0;
    float k5 = 2.0;
    float k6 = 5.2;
    float k7 = 4.0;
    float k8 = 6.2;
	
	float l  = length( p );
    float l2 = pow( l * k1, k2 );
	float n0 = noise( vec2( atan(  p.y,  p.x ) * k0, l2 ) * k3 );
	float n1 = noise( vec2( atan( -p.y, -p.x ) * k0, l2 ) * k3 );
	float n  = pow( max( n0, n1 ), k4 ) * pow( clamp( 1.0 - l * k5, 0.0, 1.0 ), k6 );
	n += pow( clamp( 1.0 - ( l * k7 - 0.1 ), 0.0, 1.0 ), k8 );
	return n;
}


void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
	vec2 iResolution = imageSize(image);
    // Normalized pixel coordinates (from 0 to 1)
    vec2 p = fragCoord / min( iResolution.x, iResolution.y );
    
    p -= 0.5; p.x -= 0.35;
    p *= PushConstants.data1.y;
    
	float r = star_burst( p * 1.05 );
	float g = star_burst( p );
	float b = star_burst( p * 0.95 );

    // Output to screen
    vec3 col = pow( vec3( r, g, b ), vec3( 1.0 / 2.2 ) );
    fragColor = vec4( col, 1.0 );
}

void main() 
{
	vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(image);
    if(texelCoord.x < size.x && texelCoord.y < size.y)
    {
        vec4 color;
        mainImage(color,texelCoord);

    
        imageStore(image, texelCoord, color);
    }   
}